project:
  type: website
  output-dir: docs

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


project:
  type: website
  output-dir: docs

website:
  title: "My Course Title"

  page-navigation: true

  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Syllabus"
        href: syllabus.qmd
      - text: "Lectures"
        href: lectures.qmd
      - text: "Homework"
        href: homework.qmd

  navbar:
    title: "My Course Title"
    left: []

