project:
  type: website
  output-dir: docs

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

website:
  title: "My Course Title"

  sidebar:
    style: "docked"
    collapse-level: 1
    contents:
      - text: "Syllabus"
        href: syllabus.qmd
      - text: "Lectures"
        href: lectures.qmd
      - text: "Homework"
        href: homework.qmd

  navbar:
    title: "My Course Title"
    left: []

